openapi: 3.0.0
info:
  title: compileApi
  version: 1.0.0
servers:
  - url: http://localhost:9000
paths:
  /compile:
    post:
      tags:
        - default
      summary: compile a code
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                language: python
                codeText: print('helo')
      responses:
        default:
          description: Successful response
          content:
            application/json: { }
        "200":
          description: Successful response
          content:
            application/json: {}