name: Create Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing catalyst
        run : npm i -g zcatalyst-cli
      - name: Deploying code to catalyst
        run: ls /home/runner/work/compiler && catalyst deploy --project ${{ secrets.CATALYST_PROJECT_NAME}} --org ${{ secrets.CATALYST_ORG}} --token ${{ secrets.CATALYST_TOKEN}}